name: CI
on:
  workflow_dispatch:
  push:
    branches: [ rolling ]
  pull_request:
    branches: [ rolling ]
    paths-ignore:
      - "*.md"
      - ".gitattributes"
      - ".gitignore"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  test:
    name: "Test with Bun"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Warming up (bun)
        uses: oven-sh/setup-bun@v1

      - name: Warming up (deps)
        run: bun i

      - name: Cheking tests... (bun)
        run: bun run test

  node-test:
    name: "Test with Node v${{ matrix.node }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 16.x, 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Warming up (bun)
        uses: oven-sh/setup-bun@v1

      - name: Warming up (node)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Warming up (deps)
        run: bun i

      - if: ${{ matrix.node == '16.x' }}
        name: Warming up (special-deps)
        run: bun i undici

      - if: ${{ matrix.node != '16.x' }}
        name: Cheking tests... (node)
        run: bun run node:test

      # Cloudflare WAF triggers with "undici" and GitHub Runners
      - if: ${{ matrix.node == '16.x' }}
        name: Cheking tests... (special-node)
        continue-on-error: true
        run: bun run node:test

      - if: ${{ always() && github.repository_owner == 'jspaste' && matrix.node == '20.x' }}
        name: Report to Codecov...
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage-final.json