name: ci
on:
  push:
    branches: [ rolling ]
  pull_request:
    branches: [ rolling ]
    paths-ignore:
      - "*.md"
      - ".gitattributes"
      - ".gitignore"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  test:
    name: "Test with Node v${{ matrix.node }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Warming up (node)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Warming up (deps)
        run: npm ci

      - name: Cheking tests...
        run: npm run test

      - if: always() && github.repository_owner == 'jspaste' && ${{ matrix.node }} == '18.x'
        name: Report to Codecov...
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage-final.json